#!/usr/bin/env sh
WS=workspace
S=@d10221 # scope
DIR=`dirname $0`
$DIR/ws tiny-sql-connect test
$DIR/ws tiny-sql-params test
$DIR/ws tiny-sql-exec-sql test
$DIR/ws tiny-sql-connection-string-parse test
$DIR/ws tiny-sql-connection-config test
$DIR/ws tiny-sql-connection-factory test
$DIR/ws tiny-sql-with-sql-connection cuild
$DIR/ws tiny-sql-use-connection test