#!/usr/bin/env sh
WS=workspace
S=@d10221 # scope
DIR=`dirname $0`
$DIR/ws tiny-sql-connect $@
$DIR/ws tiny-sql-params $@
$DIR/ws tiny-sql-exec-sql $@
$DIR/ws tiny-sql-connection-string-parse $@
$DIR/ws tiny-sql-connection-config $@
$DIR/ws tiny-sql-connection-factory $@
$DIR/ws tiny-sql-with-sql-connection cuild
$DIR/ws tiny-sql-use-connection $@